COMPONENTS = Stack.class ThreadID.class Profiler.class Pool.class LockFreeStack.class Partial.class SimplePartial.class AdvancedPartial.class	\
Sudoku.class ConcurrentSudoku.class

all: $(COMPONENTS)

%.class: %.scala
	 fsc $<
